/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FormationTemplate {
  'id' : TemplateId,
  'formation' : string,
  'name' : string,
  'lineupDataJson' : string,
  'benchPlayers' : Array<PlayerId>,
}
export interface Match {
  'id' : MatchId,
  'result' : [] | [string],
  'date' : string,
  'notes' : string,
  'opponent' : string,
}
export interface MatchAvailability {
  'matchId' : MatchId,
  'availablePlayers' : Array<PlayerId>,
}
export type MatchId = bigint;
export interface Player {
  'id' : PlayerId,
  'name' : string,
  'jerseyNumber' : bigint,
  'notes' : string,
  'positions' : Array<string>,
}
export type PlayerId = bigint;
export type TemplateId = bigint;
export interface _SERVICE {
  /**
   * / ******* Formation Template Management ********
   */
  'addFormationTemplate' : ActorMethod<
    [string, string, string, Array<PlayerId>],
    TemplateId
  >,
  /**
   * / ******* Match Management ********
   */
  'addMatch' : ActorMethod<[string, string, string], MatchId>,
  /**
   * / ******* Player Management ********
   */
  'addPlayer' : ActorMethod<[string, bigint, Array<string>, string], PlayerId>,
  'deleteFormationTemplate' : ActorMethod<[TemplateId], undefined>,
  'deleteMatch' : ActorMethod<[MatchId], undefined>,
  'deletePlayer' : ActorMethod<[PlayerId], undefined>,
  'getAllFormationTemplates' : ActorMethod<[], Array<FormationTemplate>>,
  'getAllMatchAvailabilities' : ActorMethod<[], Array<MatchAvailability>>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getFormationTemplate' : ActorMethod<[TemplateId], FormationTemplate>,
  'getMatch' : ActorMethod<[MatchId], Match>,
  'getMatchAvailability' : ActorMethod<[MatchId], Array<PlayerId>>,
  'getPlayer' : ActorMethod<[PlayerId], Player>,
  /**
   * / ******* Match Availability Management ********
   */
  'setMatchAvailability' : ActorMethod<[MatchId, Array<PlayerId>], undefined>,
  'updateFormationTemplate' : ActorMethod<
    [TemplateId, string, string, string, Array<PlayerId>],
    undefined
  >,
  'updateMatch' : ActorMethod<
    [MatchId, string, string, string, [] | [string]],
    undefined
  >,
  'updatePlayer' : ActorMethod<
    [PlayerId, string, bigint, Array<string>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];