/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerId = IDL.Nat;
export const TemplateId = IDL.Nat;
export const MatchId = IDL.Nat;
export const FormationTemplate = IDL.Record({
  'id' : TemplateId,
  'formation' : IDL.Text,
  'name' : IDL.Text,
  'lineupDataJson' : IDL.Text,
  'benchPlayers' : IDL.Vec(PlayerId),
});
export const MatchAvailability = IDL.Record({
  'matchId' : MatchId,
  'availablePlayers' : IDL.Vec(PlayerId),
});
export const Match = IDL.Record({
  'id' : MatchId,
  'result' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'opponent' : IDL.Text,
});
export const Player = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'jerseyNumber' : IDL.Nat,
  'notes' : IDL.Text,
  'positions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addFormationTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(PlayerId)],
      [TemplateId],
      [],
    ),
  'addMatch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [MatchId], []),
  'addPlayer' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
      [PlayerId],
      [],
    ),
  'deleteFormationTemplate' : IDL.Func([TemplateId], [], []),
  'deleteMatch' : IDL.Func([MatchId], [], []),
  'deletePlayer' : IDL.Func([PlayerId], [], []),
  'getAllFormationTemplates' : IDL.Func(
      [],
      [IDL.Vec(FormationTemplate)],
      ['query'],
    ),
  'getAllMatchAvailabilities' : IDL.Func(
      [],
      [IDL.Vec(MatchAvailability)],
      ['query'],
    ),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getFormationTemplate' : IDL.Func(
      [TemplateId],
      [FormationTemplate],
      ['query'],
    ),
  'getMatch' : IDL.Func([MatchId], [Match], ['query']),
  'getMatchAvailability' : IDL.Func([MatchId], [IDL.Vec(PlayerId)], ['query']),
  'getPlayer' : IDL.Func([PlayerId], [Player], ['query']),
  'setMatchAvailability' : IDL.Func([MatchId, IDL.Vec(PlayerId)], [], []),
  'updateFormationTemplate' : IDL.Func(
      [TemplateId, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(PlayerId)],
      [],
      [],
    ),
  'updateMatch' : IDL.Func(
      [MatchId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updatePlayer' : IDL.Func(
      [PlayerId, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerId = IDL.Nat;
  const TemplateId = IDL.Nat;
  const MatchId = IDL.Nat;
  const FormationTemplate = IDL.Record({
    'id' : TemplateId,
    'formation' : IDL.Text,
    'name' : IDL.Text,
    'lineupDataJson' : IDL.Text,
    'benchPlayers' : IDL.Vec(PlayerId),
  });
  const MatchAvailability = IDL.Record({
    'matchId' : MatchId,
    'availablePlayers' : IDL.Vec(PlayerId),
  });
  const Match = IDL.Record({
    'id' : MatchId,
    'result' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'opponent' : IDL.Text,
  });
  const Player = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'jerseyNumber' : IDL.Nat,
    'notes' : IDL.Text,
    'positions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addFormationTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(PlayerId)],
        [TemplateId],
        [],
      ),
    'addMatch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [MatchId], []),
    'addPlayer' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
        [PlayerId],
        [],
      ),
    'deleteFormationTemplate' : IDL.Func([TemplateId], [], []),
    'deleteMatch' : IDL.Func([MatchId], [], []),
    'deletePlayer' : IDL.Func([PlayerId], [], []),
    'getAllFormationTemplates' : IDL.Func(
        [],
        [IDL.Vec(FormationTemplate)],
        ['query'],
      ),
    'getAllMatchAvailabilities' : IDL.Func(
        [],
        [IDL.Vec(MatchAvailability)],
        ['query'],
      ),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getFormationTemplate' : IDL.Func(
        [TemplateId],
        [FormationTemplate],
        ['query'],
      ),
    'getMatch' : IDL.Func([MatchId], [Match], ['query']),
    'getMatchAvailability' : IDL.Func(
        [MatchId],
        [IDL.Vec(PlayerId)],
        ['query'],
      ),
    'getPlayer' : IDL.Func([PlayerId], [Player], ['query']),
    'setMatchAvailability' : IDL.Func([MatchId, IDL.Vec(PlayerId)], [], []),
    'updateFormationTemplate' : IDL.Func(
        [TemplateId, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(PlayerId)],
        [],
        [],
      ),
    'updateMatch' : IDL.Func(
        [MatchId, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updatePlayer' : IDL.Func(
        [PlayerId, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };