/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PlayerId = bigint;
export interface Player {
    id: PlayerId;
    name: string;
    jerseyNumber: bigint;
    notes: string;
    positions: Array<string>;
}
export interface MatchAvailability {
    matchId: MatchId;
    availablePlayers: Array<PlayerId>;
}
export type TemplateId = bigint;
export interface FormationTemplate {
    id: TemplateId;
    formation: string;
    name: string;
    lineupDataJson: string;
    benchPlayers: Array<PlayerId>;
}
export interface Match {
    id: MatchId;
    result?: string;
    date: string;
    notes: string;
    opponent: string;
}
export type MatchId = bigint;
export interface backendInterface {
    /**
     * / ******* Formation Template Management ********
     */
    addFormationTemplate(name: string, formation: string, lineupDataJson: string, benchPlayers: Array<PlayerId>): Promise<TemplateId>;
    /**
     * / ******* Match Management ********
     */
    addMatch(opponent: string, date: string, notes: string): Promise<MatchId>;
    /**
     * / ******* Player Management ********
     */
    addPlayer(name: string, jerseyNumber: bigint, positions: Array<string>, notes: string): Promise<PlayerId>;
    deleteFormationTemplate(id: TemplateId): Promise<void>;
    deleteMatch(id: MatchId): Promise<void>;
    deletePlayer(id: PlayerId): Promise<void>;
    getAllFormationTemplates(): Promise<Array<FormationTemplate>>;
    getAllMatchAvailabilities(): Promise<Array<MatchAvailability>>;
    getAllMatches(): Promise<Array<Match>>;
    getAllPlayers(): Promise<Array<Player>>;
    getFormationTemplate(id: TemplateId): Promise<FormationTemplate>;
    getMatch(id: MatchId): Promise<Match>;
    getMatchAvailability(matchId: MatchId): Promise<Array<PlayerId>>;
    getPlayer(id: PlayerId): Promise<Player>;
    /**
     * / ******* Match Availability Management ********
     */
    setMatchAvailability(matchId: MatchId, availablePlayers: Array<PlayerId>): Promise<void>;
    updateFormationTemplate(id: TemplateId, name: string, formation: string, lineupDataJson: string, benchPlayers: Array<PlayerId>): Promise<void>;
    updateMatch(id: MatchId, opponent: string, date: string, notes: string, result: string | null): Promise<void>;
    updatePlayer(id: PlayerId, name: string, jerseyNumber: bigint, positions: Array<string>, notes: string): Promise<void>;
}
import type { Match as _Match, MatchId as _MatchId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFormationTemplate(arg0: string, arg1: string, arg2: string, arg3: Array<PlayerId>): Promise<TemplateId> {
        if (this.processError) {
            try {
                const result = await this.actor.addFormationTemplate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFormationTemplate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addMatch(arg0: string, arg1: string, arg2: string): Promise<MatchId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMatch(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMatch(arg0, arg1, arg2);
            return result;
        }
    }
    async addPlayer(arg0: string, arg1: bigint, arg2: Array<string>, arg3: string): Promise<PlayerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteFormationTemplate(arg0: TemplateId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFormationTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFormationTemplate(arg0);
            return result;
        }
    }
    async deleteMatch(arg0: MatchId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async deletePlayer(arg0: PlayerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async getAllFormationTemplates(): Promise<Array<FormationTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFormationTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFormationTemplates();
            return result;
        }
    }
    async getAllMatchAvailabilities(): Promise<Array<MatchAvailability>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatchAvailabilities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatchAvailabilities();
            return result;
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return result;
        }
    }
    async getFormationTemplate(arg0: TemplateId): Promise<FormationTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.getFormationTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFormationTemplate(arg0);
            return result;
        }
    }
    async getMatch(arg0: MatchId): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_Match_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_Match_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchAvailability(arg0: MatchId): Promise<Array<PlayerId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchAvailability(arg0);
            return result;
        }
    }
    async getPlayer(arg0: PlayerId): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return result;
        }
    }
    async setMatchAvailability(arg0: MatchId, arg1: Array<PlayerId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMatchAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMatchAvailability(arg0, arg1);
            return result;
        }
    }
    async updateFormationTemplate(arg0: TemplateId, arg1: string, arg2: string, arg3: string, arg4: Array<PlayerId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFormationTemplate(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFormationTemplate(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMatch(arg0: MatchId, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updatePlayer(arg0: PlayerId, arg1: string, arg2: bigint, arg3: Array<string>, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_Match_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    result: [] | [string];
    date: string;
    notes: string;
    opponent: string;
}): {
    id: MatchId;
    result?: string;
    date: string;
    notes: string;
    opponent: string;
} {
    return {
        id: value.id,
        result: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.result)),
        date: value.date,
        notes: value.notes,
        opponent: value.opponent
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
